config/routes.rb
Rails.application.routes.draw do
  get 'starship/index'

  get 'planet/index'

  get 'character/index'

  get 'pelicula/index'
  get    '/search',     to: 'welcome#search'
  root 'welcome#index'
  get '/welcome', to: 'welcome#index' 
  get '/pelicula', to: 'pelicula#index'
  get '/character', to: 'character#index'
  get '/planet', to: 'planet#index'
  get '/starship', to: 'starship#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/character_controller.rb
class CharacterController < ApplicationController
  def index
    self.params = params.permit!
  	@informacion = params[:content]
  	url_c = HTTParty.get('https://swapi.co/api/films/')
  	url_c = JSON.parse(url_c.body)
  	@films = []
  	@lista = @informacion["films"]
  if @lista != nil
	url_c["results"].each do |c| 
		if @lista.include? c["url"]
			@films.push(c)
	    end
    end
  end

	@starship = @informacion["starships"]
    @starships = []   
    if @starship != nil
        diccionario = []
        url = 'https://swapi.co/api/starships/?page=1'
        while url != nil do
            personas = HTTParty.get(url)
            personas = JSON.parse(personas.body)
            contenido = personas["results"]
            diccionario.concat(contenido)
            url = personas["next"]
        end
        url_c = diccionario
      url_c.each do |c| 
      	if @starship.include? c["url"]
      		@starships.push(c)
        end	
      end
    else
      @starships = []
    end

  planeta = HTTParty.get(@informacion["homeworld"])
  planeta = JSON.parse(planeta.body)
  @planets = planeta



  end

end

app/controllers/pelicula_controller.rb
require "rubygems"
require "httparty"

class PeliculaController < ApplicationController
  include HTTParty
  def index

    
  	self.params = params.permit!
	@urls =  params[:informacion]
	@title = @urls["title"]
	@episode = @urls["episode_id"]
	@description = @urls["opening_crawl"]
	@director = @urls["director"]
	@producer = @urls["producer"]
	@año = @urls["release_date"]
	@character = @urls["characters"]
    @informacion = @urls


    @characters = []   
        diccionario = []
        url = 'https://swapi.co/api/people/?page=1'
        while url != nil do
            personas = HTTParty.get(url)
            personas = JSON.parse(personas.body)
            contenido = personas["results"]
            diccionario.concat(contenido)
            url = personas["next"]
        end
        url_c = diccionario
    url_c.each do |c| 
    	if @character.include? c["url"] 
    		@characters.push(c)
        end	
    end
    @planet = @urls["planets"]
    @planets = []  
        diccionario = []
        url = 'https://swapi.co/api/planets/?page=1'
        while url != nil do
            personas = HTTParty.get(url)
            personas = JSON.parse(personas.body)
            contenido = personas["results"]
            diccionario.concat(contenido)
            url = personas["next"]
        end
        url_c = diccionario
    url_c.each do |c| 
    	if @planet.include? c["url"]
    		@planets.push(c)
        end	
    end
	
	@starship = @urls["starships"]
    @starships = []   
        diccionario = []
        url = 'https://swapi.co/api/starships/?page=1'
        while url != nil do
            personas = HTTParty.get(url)
            personas = JSON.parse(personas.body)
            contenido = personas["results"]
            diccionario.concat(contenido)
            url = personas["next"]
        end
        url_c = diccionario
    url_c.each do |c| 
    	if @starship.include? c["url"]
    		@starships.push(c)
        end	
    end
    @url_c = url_c



  end
end

app/controllers/planet_controller.rb
class PlanetController < ApplicationController
  def index
  	self.params = params.permit!
  	@informacion = params[:content]
  	@hola = params[:hola]
  	url_c = HTTParty.get('https://swapi.co/api/films/')
  	url_c = JSON.parse(url_c.body)
  	@films = []
  	@lista = @informacion["films"]
  if @lista != nil
	url_c["results"].each do |c| 
		if @lista.include? c["url"]
			@films.push(c)
	    end
  end
    end

	@residente = @informacion["residents"]
    @residentes = []   
        diccionario = []
        url = 'https://swapi.co/api/people/?page=1'
        while url != nil do
            personas = HTTParty.get(url)
            personas = JSON.parse(personas.body)
            contenido = personas["results"]
            diccionario.concat(contenido)
            url = personas["next"]
        end
        url_c = diccionario
    if @residente != nil

	    url_c.each do |c| 
	    	if @residente.include? c["url"]
	    		@residentes.push(c)
	        end	
	    end
	else
		@residentes = []
	end





  end

end

app/controllers/starship_controller.rb
class StarshipController < ApplicationController
  def index
  	@informacion = params[:content]
  	url_c = HTTParty.get('https://swapi.co/api/films/')
  	url_c = JSON.parse(url_c.body)
  	@films = []
  	@lista = @informacion["films"]
  if @lista != nil
	url_c["results"].each do |c| 
		if @lista.include? c["url"]
			@films.push(c)
	    end
    end
  end
  @character = @informacion["pilots"]
  @pilots = []   
        diccionario = []
        url = 'https://swapi.co/api/people/?page=1'
        while url != nil do
            personas = HTTParty.get(url)
            personas = JSON.parse(personas.body)
            contenido = personas["results"]
            diccionario.concat(contenido)
            url = personas["next"]
        end
        url_c = diccionario
    if @character != nil

      url_c.each do |c| 
        if @character.include? c["url"] 
          @pilots.push(c)
          end
       end

    end
  end
end

app/controllers/welcome_controller.rb
require "rubygems"
require "httparty"
class WelcomeController < ApplicationController
  include HTTParty
  def index
	response1 = HTTParty.get('https://swapi.co/api/films/')
	@response = JSON.parse(response1.body)

  end

    def search
	 	response1 = HTTParty.get('https://swapi.co/api/films/')
		response = JSON.parse(response1.body)
		@films = response["results"]
    	@parametros = params[:searchbox]
    	diccionario = []
    	url = 'https://swapi.co/api/people/?page=1'
    	while url != nil do
    		personas = HTTParty.get(url)
    		personas = JSON.parse(personas.body)
    		contenido = personas["results"]
    		diccionario.concat(contenido)
    		url = personas["next"]
    	end
    	@personas = diccionario
    	diccionario = []
    	url = 'https://swapi.co/api/planets/?page=1'
    	while url != nil do
    		personas = HTTParty.get(url)
    		personas = JSON.parse(personas.body)
    		contenido = personas["results"]
    		diccionario.concat(contenido)
    		url = personas["next"]
    	end
    	@planets = diccionario
    	diccionario = []
    	url = 'https://swapi.co/api/starships/?page=1'
    	while url != nil do
    		personas = HTTParty.get(url)
    		personas = JSON.parse(personas.body)
    		contenido = personas["results"]
    		diccionario.concat(contenido)
    		url = personas["next"]
    	end
    	@starships = diccionario
    	


    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/character_helper.rb
module CharacterHelper
end

app/helpers/pelicula_helper.rb
module PeliculaHelper
end

app/helpers/planet_helper.rb
module PlanetHelper
end

app/helpers/starship_helper.rb
module StarshipHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/character/index.html.erb
<h1>STAR WAR CHARACTER</h1>


<table>
    <thead>
       <tr>
        <th>Name: </th>
        <th><%= @informacion["name"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Birth year: </th>
       	<th><%= @informacion["birth_year"] %></th>
 		

       </tr>
    </thead>
</table>


<table>
    <thead>
       <tr>
       	<th>Eye color: </th>
       	<th><%= @informacion["eye_color"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Gender: </th>
       	<th><%= @informacion["gender"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Hair color: </th>
       	<th><%= @informacion["hair_color"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Height: </th>
       	<th><%= @informacion["height"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Mass: </th>
       	<th><%= @informacion["mass"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Name: </th>
       	<th><%= @informacion["name"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Skin color: </th>
       	<th><%= @informacion["skin_color"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Films: </th>
       </tr>
    </thead>
    <tbody>
		<%  @films.each do |film| %>
       	<td> </td>
       	<td><%= link_to film["title"], pelicula_path(:informacion=> film ), class: "btn btn-primary" %></td>
    	 </tr>
         <% end %>
    </tbody>
</table>


<table>
    <thead>
       <tr>
        <th>Homeworld:  </th>
        <th><%=  link_to @planets["name"], planet_path(:content=> @planets), class: "btn btn-primary" %></th>
       </tr>
    </thead>
</table>




<table>
    <thead>
       <tr>
       	<th>Starships: </th>
       </tr>
    </thead>
    <tbody>
		<%  @starships.each do |film| %>
       	<td> </td>
       	<td><%= link_to film["name"], starship_path(:content=> film ), class: "btn btn-primary" %></td>
    	 </tr>
         <% end %>
    </tbody>
</table>


<table>
    <thead>
       <tr>
        <th>Created: </th>
        <th><%= @informacion["created"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
        <th>Edited: </th>
        <th><%= @informacion["edited"] %></th>
       </tr>
    </thead>
</table>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<nav>
        <td><%= link_to "STARWARS", welcome_path, class: "btn btn-primary" %></td>
	<h1> </h1>
          <%= form_tag({:controller => "welcome", :action => "search"},:method => :get) do %>
              <div align="center">
              <div class = "busqueda_label">
              Ingrese Búsqueda
              </div>
              <%= text_field_tag "searchbox", params[:searchbox] , class: ""%>
              <%= submit_tag "Buscar", :name => nil, class: "boton_busqueda" %>
              </div>
            <% end %>
     <h1> </h1>
</nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Example</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/pelicula/index.html.erb
<h1>STAR WARS PELÍCULA</h1>
	



<table>
    <thead>
       <tr>
       	<th>Título: </th>
       	<th><%= @title %></th>
 		

       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Episodio: </th>
       	<th><%= @episode %></th>
  

       </tr>
    </thead>
</table>
<table>
    <thead>
       <tr>	
       	<th>Descripción: </th>
        <th colspan=10> </th>
       </tr>
    </thead>
    <tbody>
    <th colspan=10> </th>
    <th><%= @description %></th>
  </tbody>
</table>
<table>
    <thead>
       <tr>
       	<th>Director: </th>
       	<th><%= @director%></th>


       </tr>
    </thead>
</table>
<table>
    <thead>
       <tr>
       	<th>Productor: </th>
       	<th><%= @producer%></th>

       </tr>
    </thead>
</table>
<table>
    <thead>
       <tr>
       	<th>Año: </th>
       	<th><%= @año %></th>


       </tr>
    </thead>
</table>
<table>
    <thead>
       <tr>
       	<th>Characters: </th>
       	<th>  </th>
       </tr>
    </thead>
    <tbody>
		<%  @characters.each do |character| %>
       	<td> </td>
       	<td><%= link_to character["name"], character_path(:content=> character ), class: "btn btn-primary" %></td>
    	 </tr>
         <% end %>
    </tbody>
</table>
<table>
    <thead>
       <tr>
       	<th>Planetas: </th>
       </tr>
    </thead>
    <tbody>
		<%  @planets.each do |planet| %>
       	<td> </td>
       	<td><%= link_to planet["name"], planet_path(:content=> planet, :hola=>@character), class: "btn btn-primary" %></td>
    	 </tr>
         <% end %>
    </tbody>
</table>
<table>
    <thead>
       <tr>
       	<th>Starships: </th>
       </tr>
    </thead>
    <tbody>
		<%  @starships.each do |starship| %>
       	<td> </td>
       	<td><%= link_to starship["name"], starship_path(:content=> starship ), class: "btn btn-primary" %></td>
    	 </tr>
         <% end %>
    </tbody>
</table>

<table>
    <thead>
       <tr>
        <th>Created: </th>
        <th><%= @informacion["created"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
        <th>Edited: </th>
        <th><%= @informacion["edited"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
        <th>Url: </th>
        <th><%= @informacion["url"] %></th>
       </tr>
    </thead>
</table>

app/views/planet/index.html.erb
<h1>STAR WARS PLANET</h1>

<table>
    <thead>
       <tr>
       	<th>Name: </th>
 		   <th><%= @informacion["name"] %></th>

       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Rotation period: </th>
       	<th><%= @informacion["rotation_period"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Orbital period: </th>
       	<th><%= @informacion["orbital_period"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Diameter: </th>
       	<th><%= @informacion["diameter"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Climate: </th>
       	<th><%= @informacion["climate"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Gravity: </th>
       	<th><%= @informacion["gravity"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Terrain: </th>
       	<th><%= @informacion["terrain"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Surface water: </th>
       	<th><%= @informacion["surface_water"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Population: </th>
       	<th><%= @informacion["population"] %></th>
       </tr>
    </thead>
</table>


<table>
    <thead>
       <tr>
       	<th>Films: </th>
       </tr>
    </thead>
    <tbody>
		<%  @films.each do |film| %>
       	<td> </td>
       	<td><%= link_to film["title"], pelicula_path(:informacion=> film), class: "btn btn-primary" %></td>
    	 </tr>
         <% end %>
    </tbody>
</table>


<table>
    <thead>
       <tr>
       	<th>Residents: </th>
       </tr>
    </thead>
    <tbody>
		<%  @residentes.each do |residente| %>
       	<td> </td>
       	<td><%= link_to residente["name"], character_path(:content=> residente ), class: "btn btn-primary" %></td>
    	 </tr>
         <% end %>
    </tbody>
</table>

<table>
    <thead>
       <tr>
       	<th>Created: </th>
       	<th><%= @informacion["created"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Edited: </th>
       	<th><%= @informacion["edited"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Url: </th>
       	<th><%= @informacion["url"] %></th>
       </tr>
    </thead>
</table>

app/views/starship/index.html.erb
<h1>STAR WAR STARSHIP</h1>


<table>
    <thead>
       <tr>
       	<th>Name: </th>
       	<th><%= @informacion["name"] %></th>
 		

       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Model: </th>
       	<th><%= @informacion["model"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Manufacturer: </th>
       	<th><%= @informacion["manufacturer"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Cost in credits: </th>
       	<th><%= @informacion["cost_in_credits"] %></th>
       </tr>
    </thead>
</table>


<table>
    <thead>
       <tr>
       	<th>Length: </th>
       	<th><%= @informacion["length"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>max_atmosphering_speed: </th>
       	<th><%= @informacion["max_atmosphering_speed"] %></th>
       </tr>
    </thead>
</table>


<table>
    <thead>
       <tr>
       	<th>Crew: </th>
       	<th><%= @informacion["crew"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Passengers: </th>
       	<th><%= @informacion["passengers"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Cargo capacity: </th>
       	<th><%= @informacion["cargo_capacity"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Consumables: </th>
       	<th><%= @informacion["consumables"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Hyperdrive rating: </th>
       	<th><%= @informacion["hyperdrive_rating"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Mglt: </th>
       	<th><%= @informacion["MGLT"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>starship_class: </th>
       	<th><%= @informacion["starship_class"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Films: </th>
       </tr>
    </thead>
    <tbody>
		<%  @films.each do |film| %>
       	<td> </td>
       	<td><%= link_to film["title"], pelicula_path(:informacion=> film ), class: "btn btn-primary" %></td>
    	 </tr>
         <% end %>
    </tbody>
</table>

<table>
    <thead>
       <tr>
        <th>Pilots: </th>
       </tr>
    </thead>
    <tbody>
    <%  @pilots.each do |pilot| %>
        <td> </td>
        <td><%= link_to pilot["name"], character_path(:content=> pilot ), class: "btn btn-primary" %></td>
       </tr>
         <% end %>
    </tbody>
</table>


<table>
    <thead>
       <tr>
       	<th>Created: </th>
       	<th><%= @informacion["created"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Edited: </th>
       	<th><%= @informacion["edited"] %></th>
       </tr>
    </thead>
</table>

<table>
    <thead>
       <tr>
       	<th>Url: </th>
       	<th><%= @informacion["url"] %></th>
       </tr>
    </thead>
</table>

app/views/welcome/index.html.erb
  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th> </th>
        <th> Año </th>
        <th> </th>
        <th> Director </th>
        <th> </th>
        <th> Productor(es)</th>
        <th> </th>
        <th> Número de episodio </th>

        <th colspan="10"></th>
      </tr>
    </thead>

    <tbody>
		<%  @response["results"].each do |persona| %>
       	<td><%= link_to persona["title"], pelicula_path(:informacion=> persona ), class: "btn btn-primary" %></td>
       	<td> | </td>
        <td><%= persona["release_date"] %></td>
        <td> | </td>
        <td><%= persona["director"] %></td>
        <td> | </td>
        <td><%= persona["producer"] %></td>
        <td> | </td>
        <td><%= persona["episode_id"] %></td>

 



    	 </tr>
         <% end %>
    </tbody>
  </table>

app/views/welcome/search.html.erb
<h1> Búsqueda </h1>


<%  @personas.each do |persona| %>
<%  if persona["name"].include? @parametros %>
       	<td><%= link_to persona["name"], character_path(:content=> persona ), class: "btn btn-primary" %></td>
		<% end %>
<% end %>

<%  @starships.each do |starship| %>
<%  if starship["name"].include? @parametros %>
       	<td><%= link_to starship["name"], starship_path(:content=> starship ), class: "btn btn-primary" %></td>
		<% end %>
<% end %>

<%  @films.each do |film| %>
<%  if film["title"].include? @parametros %>
       	<td><%= link_to film["title"], pelicula_path(:informacion=> film ), class: "btn btn-primary" %></td>
		<% end %>
<% end %>

<%  @planets.each do |planet| %>
<%  if planet["name"].include? @parametros %>
       	<td><%= link_to planet["name"], planet_path(:content=> planet, :hola=>"hola"), class: "btn btn-primary" %></td>
		<% end %>
<% end %>